## Return by Death Manor - Gothic Theme
##
## Single source of truth for colour, type, and chrome. Everything here is
## pulled from the painted textbox art in images/ui/ -- cream rim, brown
## rail, dusty plum fill, candle gold -- so code-drawn panels and painted
## panels read as one object.
##
## Loads ahead of gui.rpy / custom_screens.rpy / script.rpy.

init offset = -3

################################################################################
## Palette
################################################################################

# Ground. Warm blacks -- the manor is lit by candles, never by fluorescents.
define GOTH_VOID      = "#0d0809"
define GOTH_INK       = "#17100f"
define GOTH_INK_DEEP  = "#120c0e"
define GOTH_PANEL     = "#241a1c"
define GOTH_PANEL_HI  = "#33252a"

# Rails and rims, straight off the art pack.
define GOTH_CREAM     = "#e8d9b8"
define GOTH_CREAM_DIM = "#bead8c"
define GOTH_RAIL      = "#4a2a20"
define GOTH_RAIL_DK   = "#2e1913"

# Plum, the textbox fill colour.
define GOTH_PLUM      = "#6b5260"
define GOTH_PLUM_DK   = "#3a2a34"

# Candle gold. The primary accent -- replaces stock Ren'Py teal everywhere.
define GOTH_GOLD      = "#f2c98a"
define GOTH_GOLD_DIM  = "#c9a062"
define GOTH_BRASS     = "#d9a85c"

# Blood. Strain, the revolver, the killer.
define GOTH_BLOOD     = "#b02a2a"
define GOTH_BLOOD_HI  = "#e0433a"
define GOTH_BLOOD_DK  = "#3e1012"

# Type colours.
define GOTH_TEXT      = "#f2e8d5"
define GOTH_TEXT_SOFT = "#c9b9a2"
define GOTH_TEXT_MUTE = "#8c7a69"
define GOTH_TEXT_OFF  = "#5c4e45"

################################################################################
## Typography
################################################################################

# Display face: titles, nameplates, headings. Noto Serif Display is bundled
# under game/fonts/ (Apache 2.0, licence included alongside).
define GOTH_FONT_DISPLAY     = "fonts/NotoSerifDisplay-Medium.ttf"
define GOTH_FONT_DISPLAY_B   = "fonts/NotoSerifDisplay-SemiBold.ttf"
define GOTH_FONT_DISPLAY_I   = "fonts/NotoSerifDisplay-Italic.ttf"

# Body face: dialogue and prose. Noto Serif proper -- shorter extenders,
# bigger x-height, far more readable at 22-26px than the display cut.
define GOTH_FONT_BODY        = "fonts/NotoSerif-Regular.ttf"
define GOTH_FONT_BODY_M      = "fonts/NotoSerif-Medium.ttf"
define GOTH_FONT_BODY_B      = "fonts/NotoSerif-SemiBold.ttf"
define GOTH_FONT_BODY_I      = "fonts/NotoSerif-Italic.ttf"

################################################################################
## Chrome -- 9-slice frames generated by tools/gen_ui.py
################################################################################

define GOTH_PANEL_FRAME   = Frame("images/ui/gen/panel.png", 10, 10)
define GOTH_PANEL_DEEP    = Frame("images/ui/gen/panel_deep.png", 10, 10)
define GOTH_PANEL_PLUM    = Frame("images/ui/gen/panel_plum.png", 10, 10)
define GOTH_PANEL_BLOOD   = Frame("images/ui/gen/panel_blood.png", 8, 8)

define GOTH_BTN           = Frame("images/ui/gen/button.png", 7, 7)
define GOTH_BTN_HOVER     = Frame("images/ui/gen/button_hover.png", 7, 7)
define GOTH_BTN_FLAT      = Frame("images/ui/gen/button_flat.png", 4, 4)
define GOTH_BTN_OFF       = Frame("images/ui/gen/button_off.png", 3, 3)
define GOTH_BTN_BLOOD     = Frame("images/ui/gen/button_blood.png", 4, 4)
define GOTH_BTN_BLOOD_HI  = Frame("images/ui/gen/button_blood_hover.png", 4, 4)

define GOTH_HUDBAR        = Frame("images/ui/gen/hudbar.png", 7, 7)
define GOTH_LEAF          = Frame("images/ui/gen/leaf.png", 3, 3)
define GOTH_TAB_ON        = Frame("images/ui/gen/tab_on.png", 5, 5)
define GOTH_TAB_OFF       = Frame("images/ui/gen/tab_off.png", 3, 3)

define GOTH_SCRIM         = Frame("images/ui/gen/scrim.png", 2, 2)

# Painted art from the asset pack, finally wired up.
define GOTH_TEXTBOX_ART   = "images/ui/textbox UI.png"
define GOTH_CONVOBOX_ART  = "images/ui/textbox UI7.png"
define GOTH_NAMEBOX_ART   = "images/ui/namebox.png"

image goth_vignette = Transform("images/ui/gen/vignette.png", xysize=(1920, 1080))
image goth_divider = "images/ui/gen/divider.png"

################################################################################
## Character speech colours
################################################################################
##
## Retuned off the stock neon set (#ff7eb3 / #b388eb / #48cae4), which fought
## the candlelit palette. These are period jewel tones that still separate
## cleanly against plum.

define GOTH_C_ADRIAN   = "#ece2cf"   # bone, the amnesiac
define GOTH_C_MARIKA   = "#e5a0ab"   # dusty rose
define GOTH_C_ELISE    = "#b094c9"   # mourning amethyst
define GOTH_C_VANCE    = "#8fb8c4"   # clinical pewter
define GOTH_C_HARGROVE = "#d4a96a"   # old brass
define GOTH_C_ODILE    = "#c9a798"   # pale clay
define GOTH_C_UNKNOWN  = "#7d7066"

################################################################################
## Reusable text styles
################################################################################

# gui.init() in gui.rpy (offset -2) resets the style system, so these are
# deliberately registered later rather than alongside the defines above.
init offset = 2

style goth_title is text:
    font GOTH_FONT_DISPLAY_B
    size 34
    color GOTH_CREAM
    outlines [(2, GOTH_VOID, 0, 0)]
    kerning 2.5

style goth_subtitle is text:
    font GOTH_FONT_DISPLAY_I
    size 20
    color GOTH_TEXT_MUTE
    kerning 1.0

style goth_heading is text:
    font GOTH_FONT_DISPLAY_B
    size 22
    color GOTH_GOLD
    kerning 1.2

style goth_body is text:
    font GOTH_FONT_BODY
    size 22
    color GOTH_TEXT
    line_spacing 5

style goth_body_soft is goth_body:
    color GOTH_TEXT_SOFT
    size 20

style goth_label is text:
    font GOTH_FONT_BODY_M
    size 17
    color GOTH_TEXT_MUTE
    kerning 1.6

style goth_value is text:
    font GOTH_FONT_DISPLAY_B
    size 21
    color GOTH_TEXT

style goth_button_text is text:
    font GOTH_FONT_BODY_M
    size 22
    color GOTH_TEXT_SOFT
    hover_color GOTH_GOLD
    insensitive_color GOTH_TEXT_OFF

################################################################################
## Dialogue window -- swaps stock gui/textbox.png for the painted art pack
################################################################################
##
## These override the stock definitions in screens.rpy (init offset 0); this
## block runs at offset 2, so it wins. Geometry lives in gui.rpy.

style window:
    background Image(GOTH_TEXTBOX_ART, xalign=0.5, yalign=1.0)

## No xalign here on purpose -- setting it would override gui.name_xpos from
## gui.rpy and pin the tab to x=0, on top of the painted crest. The candle box
## art has its crest on the left (ends at x~228), so gui.name_xpos clears it.
style namebox:
    background Frame("images/ui/gen/tab_on.png", 6, 6)
    padding (26, 7, 26, 9)

style say_label:
    font GOTH_FONT_DISPLAY_B
    size 24
    color GOTH_GOLD
    outlines [(2, GOTH_VOID, 0, 0)]
    kerning 1.4
    xalign 0.5
    yalign 0.5
    line_leading 0
    line_spacing 0

style say_dialogue:
    font GOTH_FONT_BODY
    size 23
    color GOTH_TEXT
    line_spacing 5
    outlines [(2, "#0d080999", 0, 1)]

style say_thought is say_dialogue

# In-game menu choices (the `menu:` statement) -- gothic plates, not stock bars.
style choice_button:
    background GOTH_BTN
    hover_background GOTH_BTN_HOVER
    xpadding 34
    ypadding 14
    xminimum 820

style choice_button_text:
    font GOTH_FONT_BODY_M
    size 23
    color GOTH_TEXT_SOFT
    hover_color GOTH_GOLD

# Quick menu along the bottom edge -- stock Ren'Py styling clashed badly
# with the candlelit chrome.
style quick_button:
    background None
    hover_background None
    xpadding 12
    ypadding 4

style quick_button_text:
    font GOTH_FONT_BODY_M
    size 15
    color GOTH_TEXT_OFF
    hover_color GOTH_GOLD
    selected_color GOTH_GOLD
    insensitive_color "#3a302a"
    kerning 1.0

# Scrollbars. The stock gui/scrollbar/*.png have the old teal accent baked
# into the artwork, so recolouring gui.accent_color alone left them cyan.
# Overriding the styles with solids sidesteps the pre-rendered images.
style vscrollbar:
    xsize 9
    base_bar Solid(GOTH_RAIL_DK)
    thumb Solid(GOTH_GOLD_DIM)
    hover_thumb Solid(GOTH_GOLD)
    unscrollable "hide"

style hscrollbar:
    ysize 9
    base_bar Solid(GOTH_RAIL_DK)
    thumb Solid(GOTH_GOLD_DIM)
    hover_thumb Solid(GOTH_GOLD)
    unscrollable "hide"

# Main-menu / game-menu navigation column.
style navigation_button:
    xpadding 6
    ypadding 7

style navigation_button_text:
    font GOTH_FONT_DISPLAY
    size 30
    color GOTH_TEXT_MUTE
    hover_color GOTH_GOLD
    selected_color GOTH_CREAM
    insensitive_color GOTH_TEXT_OFF
    kerning 1.5

style game_menu_label_text:
    font GOTH_FONT_DISPLAY_B
    size 46
    color GOTH_GOLD
    kerning 2
